# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tso_widget_profile.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!
from PySide6 import QtCore, QtWidgets
from inc.constants import Whats_Char_Set, Whats_Profile_Name, Whats_Char_Set_Full, Whats_Account, Whats_Set_Default, \
    Whats_Region_Size, Whats_Logon_Proc, Whats_Code_Page, Whats_Rows, Whats_Columns


class UiTsoProfileDialog(object):
    def setup_ui(self, tso_profile_dialog):
        tso_profile_dialog.setObjectName("tso_profile_dialog")
        tso_profile_dialog.setWindowModality(QtCore.Qt.ApplicationModal)
        tso_profile_dialog.resize(406, 460)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(tso_profile_dialog.sizePolicy().hasHeightForWidth())
        tso_profile_dialog.setSizePolicy(size_policy)
        self.verticalLayout = QtWidgets.QVBoxLayout(tso_profile_dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.profileFrame = QtWidgets.QFrame(tso_profile_dialog)
        self.profileFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.profileFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.profileFrame.setObjectName("profileFrame")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.profileFrame)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.profileLabel = QtWidgets.QLabel(self.profileFrame)
        self.profileLabel.setObjectName("profileLabel")
        self.horizontalLayout_7.addWidget(self.profileLabel)
        self.profileEdit = QtWidgets.QLineEdit(self.profileFrame)
        self.profileEdit.setObjectName("profileEdit")
        self.horizontalLayout_7.addWidget(self.profileEdit)
        self.setDefault = QtWidgets.QCheckBox(self.profileFrame)
        self.setDefault.setObjectName("setDefault")
        self.horizontalLayout_7.addWidget(self.setDefault)
        self.verticalLayout.addWidget(self.profileFrame)
        self.accountGroupBox = QtWidgets.QGroupBox(tso_profile_dialog)
        self.accountGroupBox.setFlat(False)
        self.accountGroupBox.setObjectName("accountGroupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.accountGroupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.accountFrame = QtWidgets.QFrame(self.accountGroupBox)
        self.accountFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.accountFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.accountFrame.setObjectName("accountFrame")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.accountFrame)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.accountLabel = QtWidgets.QLabel(self.accountFrame)
        self.accountLabel.setObjectName("accountLabel")
        self.horizontalLayout_6.addWidget(self.accountLabel)
        self.accountEdit = QtWidgets.QLineEdit(self.accountFrame)
        # self.accountEdit.setClearButtonEnabled(True)
        self.accountEdit.setObjectName("accountEdit")
        self.horizontalLayout_6.addWidget(self.accountEdit)
        self.verticalLayout_3.addWidget(self.accountFrame)
        self.regionLogonFrame = QtWidgets.QFrame(self.accountGroupBox)
        self.regionLogonFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.regionLogonFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.regionLogonFrame.setObjectName("regionLogonFrame")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.regionLogonFrame)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.regionFrame = QtWidgets.QFrame(self.regionLogonFrame)
        self.regionFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.regionFrame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.regionFrame.setObjectName("regionFrame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.regionFrame)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.regionLabel = QtWidgets.QLabel(self.regionFrame)
        self.regionLabel.setObjectName("regionLabel")
        self.verticalLayout_4.addWidget(self.regionLabel)
        self.regionEdit = QtWidgets.QLineEdit(self.regionFrame)
        self.regionEdit.setInputMethodHints(QtCore.Qt.ImhPreferNumbers)
        # self.regionEdit.setClearButtonEnabled(True)
        self.regionEdit.setObjectName("regionEdit")
        self.verticalLayout_4.addWidget(self.regionEdit)
        self.horizontalLayout_8.addWidget(self.regionFrame)
        self.logonFrame = QtWidgets.QFrame(self.regionLogonFrame)
        self.logonFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.logonFrame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.logonFrame.setObjectName("logonFrame")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.logonFrame)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.logonLabel = QtWidgets.QLabel(self.logonFrame)
        self.logonLabel.setObjectName("logonLabel")
        self.verticalLayout_5.addWidget(self.logonLabel)
        self.logonEdit = QtWidgets.QLineEdit(self.logonFrame)
        # self.logonEdit.setClearButtonEnabled(True)
        self.logonEdit.setObjectName("logonEdit")
        self.verticalLayout_5.addWidget(self.logonEdit)
        self.horizontalLayout_8.addWidget(self.logonFrame)
        self.verticalLayout_3.addWidget(self.regionLogonFrame)
        self.verticalLayout.addWidget(self.accountGroupBox)
        self.codePageGroupBox = QtWidgets.QGroupBox(tso_profile_dialog)
        self.codePageGroupBox.setObjectName("codePageGroupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.codePageGroupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.codepageFrame = QtWidgets.QFrame(self.codePageGroupBox)
        self.codepageFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.codepageFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.codepageFrame.setObjectName("codepageFrame")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.codepageFrame)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.codepageLabel = QtWidgets.QLabel(self.codepageFrame)
        self.codepageLabel.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.codepageLabel.setObjectName("codepageLabel")
        self.horizontalLayout_4.addWidget(self.codepageLabel)
        self.codePageComboBox = QtWidgets.QComboBox(self.codepageFrame)
        self.codePageComboBox.setMinimumSize(QtCore.QSize(206, 0))
        self.codePageComboBox.setObjectName("codePageComboBox")
        self.horizontalLayout_4.addWidget(self.codePageComboBox)
        self.verticalLayout_2.addWidget(self.codepageFrame)
        self.charsetFrame = QtWidgets.QFrame(self.codePageGroupBox)
        self.charsetFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.charsetFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.charsetFrame.setObjectName("charsetFrame")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.charsetFrame)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.charSetLabel = QtWidgets.QLabel(self.charsetFrame)
        self.charSetLabel.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.charSetLabel.setObjectName("charSetLabel")
        self.horizontalLayout_5.addWidget(self.charSetLabel)
        self.charsetComboBox = QtWidgets.QComboBox(self.charsetFrame)
        self.charsetComboBox.setMinimumSize(QtCore.QSize(206, 0))
        self.charsetComboBox.setObjectName("charsetComboBox")
        self.horizontalLayout_5.addWidget(self.charsetComboBox)
        self.verticalLayout_2.addWidget(self.charsetFrame)
        self.verticalLayout.addWidget(self.codePageGroupBox)
        self.geometryGroup = QtWidgets.QGroupBox(tso_profile_dialog)
        self.geometryGroup.setFlat(False)
        self.geometryGroup.setObjectName("geometryGroup")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.geometryGroup)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.rowsFrame = QtWidgets.QFrame(self.geometryGroup)
        self.rowsFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.rowsFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.rowsFrame.setObjectName("rowsFrame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.rowsFrame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.rowsLabel = QtWidgets.QLabel(self.rowsFrame)
        self.rowsLabel.setMaximumSize(QtCore.QSize(60, 16777215))
        self.rowsLabel.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.rowsLabel.setObjectName("rowsLabel")
        self.horizontalLayout.addWidget(self.rowsLabel)
        self.rowSpinBox = QtWidgets.QSpinBox(self.rowsFrame)
        self.rowSpinBox.setInputMethodHints(QtCore.Qt.ImhDigitsOnly | QtCore.Qt.ImhPreferNumbers)
        self.rowSpinBox.setMinimum(10)
        self.rowSpinBox.setMaximum(90)
        self.rowSpinBox.setProperty("value", 24)
        self.rowSpinBox.setObjectName("rowSpinBox")
        self.horizontalLayout.addWidget(self.rowSpinBox)
        self.horizontalLayout_3.addWidget(self.rowsFrame)
        self.columnsFrame = QtWidgets.QFrame(self.geometryGroup)
        self.columnsFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.columnsFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.columnsFrame.setObjectName("columnsFrame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.columnsFrame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.columnsLabel = QtWidgets.QLabel(self.columnsFrame)
        self.columnsLabel.setMaximumSize(QtCore.QSize(60, 16777215))
        self.columnsLabel.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.columnsLabel.setObjectName("columnsLabel")
        self.horizontalLayout_2.addWidget(self.columnsLabel)
        self.columnSpinBox = QtWidgets.QSpinBox(self.columnsFrame)
        self.columnSpinBox.setInputMethodHints(QtCore.Qt.ImhDigitsOnly | QtCore.Qt.ImhPreferNumbers)
        self.columnSpinBox.setMinimum(40)
        self.columnSpinBox.setMaximum(200)
        self.columnSpinBox.setProperty("value", 80)
        self.columnSpinBox.setObjectName("columnSpinBox")
        self.horizontalLayout_2.addWidget(self.columnSpinBox)
        self.horizontalLayout_3.addWidget(self.columnsFrame)
        self.verticalLayout.addWidget(self.geometryGroup)
        self.buttonBox = QtWidgets.QDialogButtonBox(tso_profile_dialog)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel | QtWidgets.QDialogButtonBox.Ok | QtWidgets.QDialogButtonBox.Reset)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslate_ui(tso_profile_dialog)
        self.codePageComboBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(tso_profile_dialog)
        tso_profile_dialog.setTabOrder(self.accountEdit, self.regionEdit)
        tso_profile_dialog.setTabOrder(self.regionEdit, self.logonEdit)
        tso_profile_dialog.setTabOrder(self.logonEdit, self.codePageComboBox)
        tso_profile_dialog.setTabOrder(self.codePageComboBox, self.charsetComboBox)
        tso_profile_dialog.setTabOrder(self.charsetComboBox, self.rowSpinBox)
        tso_profile_dialog.setTabOrder(self.rowSpinBox, self.columnSpinBox)

    def retranslate_ui(self, tso_profile_dialog):
        _translate = QtCore.QCoreApplication.translate
        tso_profile_dialog.setWindowTitle(_translate("tso_profile_dialog", "ZOWE TSO Profile"))
        self.profileLabel.setText(_translate("tso_profile_dialog", "Profile Name"))
        self.profileLabel.setWhatsThis(_translate("tso_profile_dialog", Whats_Profile_Name))
        self.profileEdit.setWhatsThis(_translate("tso_profile_dialog", Whats_Profile_Name))
        self.accountGroupBox.setTitle(_translate("tso_profile_dialog", "Account"))
        self.setDefault.setText(_translate("tso_profile_dialog", "Default"))
        self.setDefault.setWhatsThis(_translate("tso_profile_dialog", Whats_Set_Default))
        self.accountLabel.setText(_translate("tso_profile_dialog", "Mainframe Account:"))
        self.accountEdit.setToolTip(_translate("tso_profile_dialog", "Your z/OS TSO/E accounting information"))
        self.accountLabel.setWhatsThis(_translate("tso_profile_dialog", Whats_Account))
        self.accountEdit.setWhatsThis(_translate("tso_profile_dialog", Whats_Account))
        self.regionLabel.setText(_translate("tso_profile_dialog", "Region Size:"))
        self.regionEdit.setToolTip(_translate("tso_profile_dialog", "Region size for the TSO/E address space"))
        self.regionEdit.setText(_translate("tso_profile_dialog", "4096"))
        self.regionLabel.setWhatsThis(_translate("tso_profile_dialog", Whats_Region_Size))
        self.regionEdit.setWhatsThis(_translate("tso_profile_dialog", Whats_Region_Size))
        self.logonLabel.setText(_translate("tso_profile_dialog", "Logon Procedure:"))
        self.logonEdit.setToolTip(_translate("tso_profile_dialog", "The logon procedure to use when creating TSO procedures on your behalf"))
        self.logonEdit.setText(_translate("tso_profile_dialog", "IZUFPROC"))
        self.logonLabel.setWhatsThis(_translate("tso_profile_dialog", Whats_Logon_Proc))
        self.logonEdit.setWhatsThis(_translate("tso_profile_dialog", Whats_Logon_Proc))
        self.codePageGroupBox.setTitle(_translate("tso_profile_dialog", "Codepage"))
        self.codePageGroupBox.setWhatsThis(_translate("tso_profile_dialog", Whats_Char_Set_Full))
        self.codepageFrame.setToolTip(_translate("tso_profile_dialog", "Codepage value for TSO/E address space to convert messages and responses from UTF-8 to EBDIC"))
        self.codepageLabel.setText(_translate("tso_profile_dialog", "Mainframe Codepage:"))
        self.codePageComboBox.setToolTip(_translate("tso_profile_dialog", "Codepage value for TSO/E address space to convert messages and responses from UTF-8 to EBCDIC"))
        self.codePageComboBox.setWhatsThis(_translate("tso_profile_dialog", Whats_Code_Page))
        self.charSetLabel.setText(_translate("tso_profile_dialog", "Character Set:"))
        self.charsetComboBox.setToolTip(_translate("tso_profile_dialog", "Character set for address space to convert messages and responses from UTF-8 to EBCDIC"))
        self.charsetComboBox.setWhatsThis(_translate("tso_profile_dialog", Whats_Char_Set))
        self.charsetComboBox.setCurrentText(_translate("tso_profile_dialog", "697"))
        self.geometryGroup.setTitle(_translate("tso_profile_dialog", "Screen size"))
        self.rowsLabel.setText(_translate("tso_profile_dialog", "Rows:"))
        self.rowSpinBox.setToolTip(_translate("tso_profile_dialog", "The number of rows on a screen"))
        self.rowsLabel.setWhatsThis(_translate("tso_profile_dialog", Whats_Rows))
        self.rowSpinBox.setWhatsThis(_translate("tso_profile_dialog", Whats_Rows))
        self.columnsLabel.setText(_translate("tso_profile_dialog", "Columns:"))
        self.columnSpinBox.setToolTip(_translate("tso_profile_dialog", "The number of columns on a screen"))
        self.columnsLabel.setWhatsThis(_translate("tso_profile_dialog", Whats_Columns))
        self.columnSpinBox.setWhatsThis(_translate("tso_profile_dialog", Whats_Columns))
